# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nerealnaya-zomba/github-repositories/remote/SFML-Game-Demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nerealnaya-zomba/github-repositories/remote/SFML-Game-Demo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"devel\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nerealnaya-zomba/github-repositories/remote/SFML-Game-Demo/CMakeFiles /home/nerealnaya-zomba/github-repositories/remote/SFML-Game-Demo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nerealnaya-zomba/github-repositories/remote/SFML-Game-Demo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named sfml-system

# Build rule for target.
sfml-system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-system
.PHONY : sfml-system

# fast build rule for target.
sfml-system/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build.make _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build
.PHONY : sfml-system/fast

#=============================================================================
# Target rules for targets named sfml-window

# Build rule for target.
sfml-window: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-window
.PHONY : sfml-window

# fast build rule for target.
sfml-window/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build.make _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build
.PHONY : sfml-window/fast

#=============================================================================
# Target rules for targets named sfml-network

# Build rule for target.
sfml-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-network
.PHONY : sfml-network

# fast build rule for target.
sfml-network/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Network/CMakeFiles/sfml-network.dir/build.make _deps/sfml-build/src/SFML/Network/CMakeFiles/sfml-network.dir/build
.PHONY : sfml-network/fast

#=============================================================================
# Target rules for targets named sfml-graphics

# Build rule for target.
sfml-graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-graphics
.PHONY : sfml-graphics

# fast build rule for target.
sfml-graphics/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build.make _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build
.PHONY : sfml-graphics/fast

#=============================================================================
# Target rules for targets named sfml-audio

# Build rule for target.
sfml-audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-audio
.PHONY : sfml-audio

# fast build rule for target.
sfml-audio/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build.make _deps/sfml-build/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build
.PHONY : sfml-audio/fast

src/core/Enemy.o: src/core/Enemy.cpp.o
.PHONY : src/core/Enemy.o

# target to build an object file
src/core/Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Enemy.cpp.o
.PHONY : src/core/Enemy.cpp.o

src/core/Enemy.i: src/core/Enemy.cpp.i
.PHONY : src/core/Enemy.i

# target to preprocess a source file
src/core/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Enemy.cpp.i
.PHONY : src/core/Enemy.cpp.i

src/core/Enemy.s: src/core/Enemy.cpp.s
.PHONY : src/core/Enemy.s

# target to generate assembly for a file
src/core/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/Enemy.cpp.s
.PHONY : src/core/Enemy.cpp.s

src/core/EnemyManager.o: src/core/EnemyManager.cpp.o
.PHONY : src/core/EnemyManager.o

# target to build an object file
src/core/EnemyManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/EnemyManager.cpp.o
.PHONY : src/core/EnemyManager.cpp.o

src/core/EnemyManager.i: src/core/EnemyManager.cpp.i
.PHONY : src/core/EnemyManager.i

# target to preprocess a source file
src/core/EnemyManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/EnemyManager.cpp.i
.PHONY : src/core/EnemyManager.cpp.i

src/core/EnemyManager.s: src/core/EnemyManager.cpp.s
.PHONY : src/core/EnemyManager.s

# target to generate assembly for a file
src/core/EnemyManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/EnemyManager.cpp.s
.PHONY : src/core/EnemyManager.cpp.s

src/core/GameCamera.o: src/core/GameCamera.cpp.o
.PHONY : src/core/GameCamera.o

# target to build an object file
src/core/GameCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/GameCamera.cpp.o
.PHONY : src/core/GameCamera.cpp.o

src/core/GameCamera.i: src/core/GameCamera.cpp.i
.PHONY : src/core/GameCamera.i

# target to preprocess a source file
src/core/GameCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/GameCamera.cpp.i
.PHONY : src/core/GameCamera.cpp.i

src/core/GameCamera.s: src/core/GameCamera.cpp.s
.PHONY : src/core/GameCamera.s

# target to generate assembly for a file
src/core/GameCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/GameCamera.cpp.s
.PHONY : src/core/GameCamera.cpp.s

src/core/GameData.o: src/core/GameData.cpp.o
.PHONY : src/core/GameData.o

# target to build an object file
src/core/GameData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/GameData.cpp.o
.PHONY : src/core/GameData.cpp.o

src/core/GameData.i: src/core/GameData.cpp.i
.PHONY : src/core/GameData.i

# target to preprocess a source file
src/core/GameData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/GameData.cpp.i
.PHONY : src/core/GameData.cpp.i

src/core/GameData.s: src/core/GameData.cpp.s
.PHONY : src/core/GameData.s

# target to generate assembly for a file
src/core/GameData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/core/GameData.cpp.s
.PHONY : src/core/GameData.cpp.s

src/entities/Bullet.o: src/entities/Bullet.cpp.o
.PHONY : src/entities/Bullet.o

# target to build an object file
src/entities/Bullet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/Bullet.cpp.o
.PHONY : src/entities/Bullet.cpp.o

src/entities/Bullet.i: src/entities/Bullet.cpp.i
.PHONY : src/entities/Bullet.i

# target to preprocess a source file
src/entities/Bullet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/Bullet.cpp.i
.PHONY : src/entities/Bullet.cpp.i

src/entities/Bullet.s: src/entities/Bullet.cpp.s
.PHONY : src/entities/Bullet.s

# target to generate assembly for a file
src/entities/Bullet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/Bullet.cpp.s
.PHONY : src/entities/Bullet.cpp.s

src/entities/LevelPortal.o: src/entities/LevelPortal.cpp.o
.PHONY : src/entities/LevelPortal.o

# target to build an object file
src/entities/LevelPortal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/LevelPortal.cpp.o
.PHONY : src/entities/LevelPortal.cpp.o

src/entities/LevelPortal.i: src/entities/LevelPortal.cpp.i
.PHONY : src/entities/LevelPortal.i

# target to preprocess a source file
src/entities/LevelPortal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/LevelPortal.cpp.i
.PHONY : src/entities/LevelPortal.cpp.i

src/entities/LevelPortal.s: src/entities/LevelPortal.cpp.s
.PHONY : src/entities/LevelPortal.s

# target to generate assembly for a file
src/entities/LevelPortal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/LevelPortal.cpp.s
.PHONY : src/entities/LevelPortal.cpp.s

src/entities/Player.o: src/entities/Player.cpp.o
.PHONY : src/entities/Player.o

# target to build an object file
src/entities/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/Player.cpp.o
.PHONY : src/entities/Player.cpp.o

src/entities/Player.i: src/entities/Player.cpp.i
.PHONY : src/entities/Player.i

# target to preprocess a source file
src/entities/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/Player.cpp.i
.PHONY : src/entities/Player.cpp.i

src/entities/Player.s: src/entities/Player.cpp.s
.PHONY : src/entities/Player.s

# target to generate assembly for a file
src/entities/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/Player.cpp.s
.PHONY : src/entities/Player.cpp.s

src/entities/Skeleton.o: src/entities/Skeleton.cpp.o
.PHONY : src/entities/Skeleton.o

# target to build an object file
src/entities/Skeleton.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/Skeleton.cpp.o
.PHONY : src/entities/Skeleton.cpp.o

src/entities/Skeleton.i: src/entities/Skeleton.cpp.i
.PHONY : src/entities/Skeleton.i

# target to preprocess a source file
src/entities/Skeleton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/Skeleton.cpp.i
.PHONY : src/entities/Skeleton.cpp.i

src/entities/Skeleton.s: src/entities/Skeleton.cpp.s
.PHONY : src/entities/Skeleton.s

# target to generate assembly for a file
src/entities/Skeleton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/Skeleton.cpp.s
.PHONY : src/entities/Skeleton.cpp.s

src/entities/Trader.o: src/entities/Trader.cpp.o
.PHONY : src/entities/Trader.o

# target to build an object file
src/entities/Trader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/Trader.cpp.o
.PHONY : src/entities/Trader.cpp.o

src/entities/Trader.i: src/entities/Trader.cpp.i
.PHONY : src/entities/Trader.i

# target to preprocess a source file
src/entities/Trader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/Trader.cpp.i
.PHONY : src/entities/Trader.cpp.i

src/entities/Trader.s: src/entities/Trader.cpp.s
.PHONY : src/entities/Trader.s

# target to generate assembly for a file
src/entities/Trader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/Trader.cpp.s
.PHONY : src/entities/Trader.cpp.s

src/entities/enemyPortal.o: src/entities/enemyPortal.cpp.o
.PHONY : src/entities/enemyPortal.o

# target to build an object file
src/entities/enemyPortal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/enemyPortal.cpp.o
.PHONY : src/entities/enemyPortal.cpp.o

src/entities/enemyPortal.i: src/entities/enemyPortal.cpp.i
.PHONY : src/entities/enemyPortal.i

# target to preprocess a source file
src/entities/enemyPortal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/enemyPortal.cpp.i
.PHONY : src/entities/enemyPortal.cpp.i

src/entities/enemyPortal.s: src/entities/enemyPortal.cpp.s
.PHONY : src/entities/enemyPortal.s

# target to generate assembly for a file
src/entities/enemyPortal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/entities/enemyPortal.cpp.s
.PHONY : src/entities/enemyPortal.cpp.s

src/graphics/Background.o: src/graphics/Background.cpp.o
.PHONY : src/graphics/Background.o

# target to build an object file
src/graphics/Background.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Background.cpp.o
.PHONY : src/graphics/Background.cpp.o

src/graphics/Background.i: src/graphics/Background.cpp.i
.PHONY : src/graphics/Background.i

# target to preprocess a source file
src/graphics/Background.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Background.cpp.i
.PHONY : src/graphics/Background.cpp.i

src/graphics/Background.s: src/graphics/Background.cpp.s
.PHONY : src/graphics/Background.s

# target to generate assembly for a file
src/graphics/Background.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Background.cpp.s
.PHONY : src/graphics/Background.cpp.s

src/graphics/Decoration.o: src/graphics/Decoration.cpp.o
.PHONY : src/graphics/Decoration.o

# target to build an object file
src/graphics/Decoration.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Decoration.cpp.o
.PHONY : src/graphics/Decoration.cpp.o

src/graphics/Decoration.i: src/graphics/Decoration.cpp.i
.PHONY : src/graphics/Decoration.i

# target to preprocess a source file
src/graphics/Decoration.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Decoration.cpp.i
.PHONY : src/graphics/Decoration.cpp.i

src/graphics/Decoration.s: src/graphics/Decoration.cpp.s
.PHONY : src/graphics/Decoration.s

# target to generate assembly for a file
src/graphics/Decoration.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Decoration.cpp.s
.PHONY : src/graphics/Decoration.cpp.s

src/graphics/Particle.o: src/graphics/Particle.cpp.o
.PHONY : src/graphics/Particle.o

# target to build an object file
src/graphics/Particle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Particle.cpp.o
.PHONY : src/graphics/Particle.cpp.o

src/graphics/Particle.i: src/graphics/Particle.cpp.i
.PHONY : src/graphics/Particle.i

# target to preprocess a source file
src/graphics/Particle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Particle.cpp.i
.PHONY : src/graphics/Particle.cpp.i

src/graphics/Particle.s: src/graphics/Particle.cpp.s
.PHONY : src/graphics/Particle.s

# target to generate assembly for a file
src/graphics/Particle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Particle.cpp.s
.PHONY : src/graphics/Particle.cpp.s

src/graphics/Trail.o: src/graphics/Trail.cpp.o
.PHONY : src/graphics/Trail.o

# target to build an object file
src/graphics/Trail.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Trail.cpp.o
.PHONY : src/graphics/Trail.cpp.o

src/graphics/Trail.i: src/graphics/Trail.cpp.i
.PHONY : src/graphics/Trail.i

# target to preprocess a source file
src/graphics/Trail.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Trail.cpp.i
.PHONY : src/graphics/Trail.cpp.i

src/graphics/Trail.s: src/graphics/Trail.cpp.s
.PHONY : src/graphics/Trail.s

# target to generate assembly for a file
src/graphics/Trail.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/graphics/Trail.cpp.s
.PHONY : src/graphics/Trail.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/systems/GameLevel.o: src/systems/GameLevel.cpp.o
.PHONY : src/systems/GameLevel.o

# target to build an object file
src/systems/GameLevel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/GameLevel.cpp.o
.PHONY : src/systems/GameLevel.cpp.o

src/systems/GameLevel.i: src/systems/GameLevel.cpp.i
.PHONY : src/systems/GameLevel.i

# target to preprocess a source file
src/systems/GameLevel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/GameLevel.cpp.i
.PHONY : src/systems/GameLevel.cpp.i

src/systems/GameLevel.s: src/systems/GameLevel.cpp.s
.PHONY : src/systems/GameLevel.s

# target to generate assembly for a file
src/systems/GameLevel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/GameLevel.cpp.s
.PHONY : src/systems/GameLevel.cpp.s

src/systems/Ground.o: src/systems/Ground.cpp.o
.PHONY : src/systems/Ground.o

# target to build an object file
src/systems/Ground.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/Ground.cpp.o
.PHONY : src/systems/Ground.cpp.o

src/systems/Ground.i: src/systems/Ground.cpp.i
.PHONY : src/systems/Ground.i

# target to preprocess a source file
src/systems/Ground.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/Ground.cpp.i
.PHONY : src/systems/Ground.cpp.i

src/systems/Ground.s: src/systems/Ground.cpp.s
.PHONY : src/systems/Ground.s

# target to generate assembly for a file
src/systems/Ground.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/Ground.cpp.s
.PHONY : src/systems/Ground.cpp.s

src/systems/Item.o: src/systems/Item.cpp.o
.PHONY : src/systems/Item.o

# target to build an object file
src/systems/Item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/Item.cpp.o
.PHONY : src/systems/Item.cpp.o

src/systems/Item.i: src/systems/Item.cpp.i
.PHONY : src/systems/Item.i

# target to preprocess a source file
src/systems/Item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/Item.cpp.i
.PHONY : src/systems/Item.cpp.i

src/systems/Item.s: src/systems/Item.cpp.s
.PHONY : src/systems/Item.s

# target to generate assembly for a file
src/systems/Item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/Item.cpp.s
.PHONY : src/systems/Item.cpp.s

src/systems/Platform.o: src/systems/Platform.cpp.o
.PHONY : src/systems/Platform.o

# target to build an object file
src/systems/Platform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/Platform.cpp.o
.PHONY : src/systems/Platform.cpp.o

src/systems/Platform.i: src/systems/Platform.cpp.i
.PHONY : src/systems/Platform.i

# target to preprocess a source file
src/systems/Platform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/Platform.cpp.i
.PHONY : src/systems/Platform.cpp.i

src/systems/Platform.s: src/systems/Platform.cpp.s
.PHONY : src/systems/Platform.s

# target to generate assembly for a file
src/systems/Platform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/Platform.cpp.s
.PHONY : src/systems/Platform.cpp.s

src/systems/Spawner.o: src/systems/Spawner.cpp.o
.PHONY : src/systems/Spawner.o

# target to build an object file
src/systems/Spawner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/Spawner.cpp.o
.PHONY : src/systems/Spawner.cpp.o

src/systems/Spawner.i: src/systems/Spawner.cpp.i
.PHONY : src/systems/Spawner.i

# target to preprocess a source file
src/systems/Spawner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/Spawner.cpp.i
.PHONY : src/systems/Spawner.cpp.i

src/systems/Spawner.s: src/systems/Spawner.cpp.s
.PHONY : src/systems/Spawner.s

# target to generate assembly for a file
src/systems/Spawner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/systems/Spawner.cpp.s
.PHONY : src/systems/Spawner.cpp.s

src/ui/AskDialogue.o: src/ui/AskDialogue.cpp.o
.PHONY : src/ui/AskDialogue.o

# target to build an object file
src/ui/AskDialogue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/AskDialogue.cpp.o
.PHONY : src/ui/AskDialogue.cpp.o

src/ui/AskDialogue.i: src/ui/AskDialogue.cpp.i
.PHONY : src/ui/AskDialogue.i

# target to preprocess a source file
src/ui/AskDialogue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/AskDialogue.cpp.i
.PHONY : src/ui/AskDialogue.cpp.i

src/ui/AskDialogue.s: src/ui/AskDialogue.cpp.s
.PHONY : src/ui/AskDialogue.s

# target to generate assembly for a file
src/ui/AskDialogue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/AskDialogue.cpp.s
.PHONY : src/ui/AskDialogue.cpp.s

src/ui/GameLoadingScreen.o: src/ui/GameLoadingScreen.cpp.o
.PHONY : src/ui/GameLoadingScreen.o

# target to build an object file
src/ui/GameLoadingScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/GameLoadingScreen.cpp.o
.PHONY : src/ui/GameLoadingScreen.cpp.o

src/ui/GameLoadingScreen.i: src/ui/GameLoadingScreen.cpp.i
.PHONY : src/ui/GameLoadingScreen.i

# target to preprocess a source file
src/ui/GameLoadingScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/GameLoadingScreen.cpp.i
.PHONY : src/ui/GameLoadingScreen.cpp.i

src/ui/GameLoadingScreen.s: src/ui/GameLoadingScreen.cpp.s
.PHONY : src/ui/GameLoadingScreen.s

# target to generate assembly for a file
src/ui/GameLoadingScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/GameLoadingScreen.cpp.s
.PHONY : src/ui/GameLoadingScreen.cpp.s

src/ui/LoadScreen.o: src/ui/LoadScreen.cpp.o
.PHONY : src/ui/LoadScreen.o

# target to build an object file
src/ui/LoadScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/LoadScreen.cpp.o
.PHONY : src/ui/LoadScreen.cpp.o

src/ui/LoadScreen.i: src/ui/LoadScreen.cpp.i
.PHONY : src/ui/LoadScreen.i

# target to preprocess a source file
src/ui/LoadScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/LoadScreen.cpp.i
.PHONY : src/ui/LoadScreen.cpp.i

src/ui/LoadScreen.s: src/ui/LoadScreen.cpp.s
.PHONY : src/ui/LoadScreen.s

# target to generate assembly for a file
src/ui/LoadScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/LoadScreen.cpp.s
.PHONY : src/ui/LoadScreen.cpp.s

src/ui/Menu.o: src/ui/Menu.cpp.o
.PHONY : src/ui/Menu.o

# target to build an object file
src/ui/Menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/Menu.cpp.o
.PHONY : src/ui/Menu.cpp.o

src/ui/Menu.i: src/ui/Menu.cpp.i
.PHONY : src/ui/Menu.i

# target to preprocess a source file
src/ui/Menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/Menu.cpp.i
.PHONY : src/ui/Menu.cpp.i

src/ui/Menu.s: src/ui/Menu.cpp.s
.PHONY : src/ui/Menu.s

# target to generate assembly for a file
src/ui/Menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/Menu.cpp.s
.PHONY : src/ui/Menu.cpp.s

src/ui/PlayerInventory.o: src/ui/PlayerInventory.cpp.o
.PHONY : src/ui/PlayerInventory.o

# target to build an object file
src/ui/PlayerInventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/PlayerInventory.cpp.o
.PHONY : src/ui/PlayerInventory.cpp.o

src/ui/PlayerInventory.i: src/ui/PlayerInventory.cpp.i
.PHONY : src/ui/PlayerInventory.i

# target to preprocess a source file
src/ui/PlayerInventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/PlayerInventory.cpp.i
.PHONY : src/ui/PlayerInventory.cpp.i

src/ui/PlayerInventory.s: src/ui/PlayerInventory.cpp.s
.PHONY : src/ui/PlayerInventory.s

# target to generate assembly for a file
src/ui/PlayerInventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/PlayerInventory.cpp.s
.PHONY : src/ui/PlayerInventory.cpp.s

src/ui/Shop.o: src/ui/Shop.cpp.o
.PHONY : src/ui/Shop.o

# target to build an object file
src/ui/Shop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/Shop.cpp.o
.PHONY : src/ui/Shop.cpp.o

src/ui/Shop.i: src/ui/Shop.cpp.i
.PHONY : src/ui/Shop.i

# target to preprocess a source file
src/ui/Shop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/Shop.cpp.i
.PHONY : src/ui/Shop.cpp.i

src/ui/Shop.s: src/ui/Shop.cpp.s
.PHONY : src/ui/Shop.s

# target to generate assembly for a file
src/ui/Shop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ui/Shop.cpp.s
.PHONY : src/ui/Shop.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... sfml-audio"
	@echo "... sfml-graphics"
	@echo "... sfml-network"
	@echo "... sfml-system"
	@echo "... sfml-window"
	@echo "... src/core/Enemy.o"
	@echo "... src/core/Enemy.i"
	@echo "... src/core/Enemy.s"
	@echo "... src/core/EnemyManager.o"
	@echo "... src/core/EnemyManager.i"
	@echo "... src/core/EnemyManager.s"
	@echo "... src/core/GameCamera.o"
	@echo "... src/core/GameCamera.i"
	@echo "... src/core/GameCamera.s"
	@echo "... src/core/GameData.o"
	@echo "... src/core/GameData.i"
	@echo "... src/core/GameData.s"
	@echo "... src/entities/Bullet.o"
	@echo "... src/entities/Bullet.i"
	@echo "... src/entities/Bullet.s"
	@echo "... src/entities/LevelPortal.o"
	@echo "... src/entities/LevelPortal.i"
	@echo "... src/entities/LevelPortal.s"
	@echo "... src/entities/Player.o"
	@echo "... src/entities/Player.i"
	@echo "... src/entities/Player.s"
	@echo "... src/entities/Skeleton.o"
	@echo "... src/entities/Skeleton.i"
	@echo "... src/entities/Skeleton.s"
	@echo "... src/entities/Trader.o"
	@echo "... src/entities/Trader.i"
	@echo "... src/entities/Trader.s"
	@echo "... src/entities/enemyPortal.o"
	@echo "... src/entities/enemyPortal.i"
	@echo "... src/entities/enemyPortal.s"
	@echo "... src/graphics/Background.o"
	@echo "... src/graphics/Background.i"
	@echo "... src/graphics/Background.s"
	@echo "... src/graphics/Decoration.o"
	@echo "... src/graphics/Decoration.i"
	@echo "... src/graphics/Decoration.s"
	@echo "... src/graphics/Particle.o"
	@echo "... src/graphics/Particle.i"
	@echo "... src/graphics/Particle.s"
	@echo "... src/graphics/Trail.o"
	@echo "... src/graphics/Trail.i"
	@echo "... src/graphics/Trail.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/systems/GameLevel.o"
	@echo "... src/systems/GameLevel.i"
	@echo "... src/systems/GameLevel.s"
	@echo "... src/systems/Ground.o"
	@echo "... src/systems/Ground.i"
	@echo "... src/systems/Ground.s"
	@echo "... src/systems/Item.o"
	@echo "... src/systems/Item.i"
	@echo "... src/systems/Item.s"
	@echo "... src/systems/Platform.o"
	@echo "... src/systems/Platform.i"
	@echo "... src/systems/Platform.s"
	@echo "... src/systems/Spawner.o"
	@echo "... src/systems/Spawner.i"
	@echo "... src/systems/Spawner.s"
	@echo "... src/ui/AskDialogue.o"
	@echo "... src/ui/AskDialogue.i"
	@echo "... src/ui/AskDialogue.s"
	@echo "... src/ui/GameLoadingScreen.o"
	@echo "... src/ui/GameLoadingScreen.i"
	@echo "... src/ui/GameLoadingScreen.s"
	@echo "... src/ui/LoadScreen.o"
	@echo "... src/ui/LoadScreen.i"
	@echo "... src/ui/LoadScreen.s"
	@echo "... src/ui/Menu.o"
	@echo "... src/ui/Menu.i"
	@echo "... src/ui/Menu.s"
	@echo "... src/ui/PlayerInventory.o"
	@echo "... src/ui/PlayerInventory.i"
	@echo "... src/ui/PlayerInventory.s"
	@echo "... src/ui/Shop.o"
	@echo "... src/ui/Shop.i"
	@echo "... src/ui/Shop.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

